### ISSUE TITLE
Campaign.bat fails when installing dependencies

### ISSUE THREAD

**Issue by beneuto** [PredixDev/guided-tutorials#1]
Running campaign.bat results in error as per log below.   On my PC, P drive is configured as a corporate network drive.

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
FAILED
Error read/writing config:  open P:\.cf\config.json: The network path was not found.
If you are behind a corporate proxy, set the 'http_proxy' and 'https_proxy' environment variables.
Commands to set proxy:
set http_proxy="http://<proxy-host>:<proxy-port>"
set https_proxy="http://<proxy-host>:<proxy-port>"

Exiting tutorial. You can manually go through the tutorial steps here
ECHO is off.

**Comment by rishabhtulsian** [comment]
You need to run the campaign.bat in an administrator prompt because it needs to install tools.
When logged in as administrator typically you don't have access to the network drive. Looks like your user home directory is on the network drive and hence the script cannot access it.

Is there a local user you can use to run the script? During the installation a plugin is installed for the CF CLI. The error you see is because the CF CLI cannot access the user home directory which is required to install plugins and use the CLI.

**Comment by beneuto** [comment]
That makes sense.   Due to authenticated proxy, I have to tether to my phone for the script downloads to work but in doing that I lose connection to the P drive.   P drive is set for HOMEDRIVE but having installed many, many tools Cloud Foundry is the first to use it.   My P drive is actually empty otherwise.   This is an issue for CF (Google shows similar problems for many users) but I have managed to work around it by setting CF_HOME and CF_PLUGIN_HOME environment variables to a more suitable location, manually reinstalling CF and then running cf once from the windows command line which then adds config.json file to the chosen location.    Then I rerun campaign.bat.

I also found issues with JDK which locked up so I ended up installing that manually too.   Nodejs also locked up the first time but installed ok on the second try.
